### PR TITLE
WIP: Meson for gtkhash

### PR DESCRIPTION
**Pull request by Salamandar**
I splitted from #390 because GTKHash gives me a hard time.

### CODE REVIEW

**Comment by ItzSwirlz** [comment]
Worked on Ubuntu 20.10 :)

**Comment by Fantu** [comment]
From a fast check in debian/:
in debian/control I think is good specify meson min version as newer that default on buster (and others): meson->meson (>= 0.50.0)
compat 9 is deprecated, is better use the 12 like what done is near all other cinnamon components: remove debian/compat, remove debhelper (>= 9), and add debhelper-compat (= 12),
other debian/rules changes need check ( disabling of dh_makeshlibs and don't remove *.la files), instead override for dh_install --list-missing will be not needed for compat 12 because dh_missing --list-missing is the default so will be ok after compat bump

**Comment by Salamandar** [comment]
LMDE4 fails because of 

```
meson.build:1:0: ERROR:  Meson version is 0.49.2 but project requires >=0.50.0.
```

Meson 50.0 enables EASY checking for library headers. I could write some more code if you really want me to downgrade the meson version required.

**Comment by ItzSwirlz** [comment]
According to https://packages.debian.org/search?keywords=meson the only reason LMDE4 would fail is if LMDE4 was based on Debian Buster/Stable, which it probably is.. It can be backported though as seen in buster-backports (@clefebvre )

**Comment by Salamandar** [comment]
@Fantu I changed the compat versions and added a min version for Meson.

The rules were already OK.

**Comment by Fantu** [comment]
instead debhelper (>= 12), should be debhelper-compat (= 12), or will don't set compat

**Comment by Salamandar** [comment]
@Fantu Fixed :)

**Comment by Fantu** [comment]
@Salamandar sorry but this is wrong another time, this is still the old/deprecated method and will also make possible build only with debhelper 12 (with =12)
with debhelper-compat (= 12) instead will set compat 12 (instead of debian/compat that can be removed) and will make possible build also with newer debhelper package
sorry if what I wrote before was bad english, here an example of the same done in another component (cinnamon): https://github.com/linuxmint/cinnamon/commit/f9ae00edd00f9ec66ba8cd31931a951f09ae167c#diff-2a13f1344504379e877324d3a0375adcbcb4cb27d7e575ad8f4618a52d6a00e0

**Comment by Salamandar** [comment]
@Fantu No problem, I also did not read correctly your message :) This should be okay now !

**Comment by Fantu** [comment]
was correct `debhelper-compat (= 12)`
from CI: 
`dh: error: Could not parse desired debhelper compat level from relation: debhelper-compat (>= 12)`

**Comment by Salamandar** [comment]
OK. I just wanted to check if that worked or not :D

**Comment by Fantu** [comment]
on lmde seems meson dep too high (debian10 have 0.49.2)

**Comment by Salamandar** [comment]
@Fantu I added a small trick to be compatible with meson 0.49.0, with a comment that tells to remove when LMDE is updated.

**Comment by ItzSwirlz** [comment]
```
> ninja -C build                                                13:35 25-03-2021
ninja: Entering directory `build'
[9/27] Compiling C object src/hash/libhash.a.p/hash-lib-crypto.c.o
FAILED: src/hash/libhash.a.p/hash-lib-crypto.c.o 
cc -Isrc/hash/libhash.a.p -Isrc/hash -I../src/hash -I. -I.. -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/nss -I/usr/include/nspr -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g '-DG_LOG_DOMAIN="nemo-gtkhash"' -DHAVE_CONFIG_H -fPIC -DIN_HASH_LIB -MD -MQ src/hash/libhash.a.p/hash-lib-crypto.c.o -MF src/hash/libhash.a.p/hash-lib-crypto.c.o.d -o src/hash/libhash.a.p/hash-lib-crypto.c.o -c ../src/hash/hash-lib-crypto.c
../src/hash/hash-lib-crypto.c:37:13: error: field ‘ctx’ has incomplete type
   37 |  EVP_MD_CTX ctx;
      |             ^~~
../src/hash/hash-lib-crypto.c: In function ‘gtkhash_hash_lib_crypto_get_md’:
../src/hash/hash-lib-crypto.c:48:11: warning: implicit declaration of function ‘EVP_sha’; did you mean ‘EVP_sha1’? [-Wimplicit-function-declaration]
   48 |    return EVP_sha();
      |           ^~~~~~~
      |           EVP_sha1
../src/hash/hash-lib-crypto.c:48:11: warning: returning ‘int’ from a function with return type ‘const EVP_MD *’ {aka ‘const struct evp_md_st *’} makes pointer from integer without a cast [-Wint-conversion]
   48 |    return EVP_sha();
      |           ^~~~~~~~~
../src/hash/hash-lib-crypto.c:54:11: warning: implicit declaration of function ‘EVP_mdc2’; did you mean ‘EVP_md5’? [-Wimplicit-function-declaration]
   54 |    return EVP_mdc2();
      |           ^~~~~~~~
      |           EVP_md5
../src/hash/hash-lib-crypto.c:54:11: warning: returning ‘int’ from a function with return type ‘const EVP_MD *’ {aka ‘const struct evp_md_st *’} makes pointer from integer without a cast [-Wint-conversion]
   54 |    return EVP_mdc2();
      |           ^~~~~~~~~~
../src/hash/hash-lib-crypto.c: In function ‘gtkhash_hash_lib_crypto_is_supported’:
../src/hash/hash-lib-crypto.c:74:2: warning: implicit declaration of function ‘EVP_MD_CTX_cleanup’; did you mean ‘EVP_MD_CTX_create’? [-Wimplicit-function-declaration]
   74 |  EVP_MD_CTX_cleanup(&data.ctx);
      |  ^~~~~~~~~~~~~~~~~~
      |  EVP_MD_CTX_create
../src/hash/hash-lib-crypto.c:64:27: warning: variable ‘data’ set but not used [-Wunused-but-set-variable]
   64 |  struct hash_lib_crypto_s data;
      |                           ^~~~
[14/27] Compiling C object src/hash/libhash.a.p/hash-lib-nettle.c.o
ninja: build stopped: subcommand failed.
>                                                               13:35 25-03-2021


```

it passed on LMDE so good enough

**Comment by Salamandar** [comment]
@ItzSwirlz because of that : https://stackoverflow.com/questions/47518843/error-field-ctx-has-incomplete-type-evp-cipher-ctx

**Comment by Salamandar** [comment]
Hum, question : https://github.com/tristanheaven/gtkhash is way more up-to-date than this extension. Is it even relevant to use this code instead of the upstream project ?

**Comment by Fantu** [comment]
probably is good rebase it, in 8 years many things was added/improved and probably do the meson port upstream instead (after rebase also include it here)
nemo support is already upstream and the only change here (from gtkhash upstream) should be only add in this repo ad subfolder and add debian/

**Comment by ItzSwirlz** [comment]
As trying to package for Debian, there is the conflictions with nemo-gtkhash. I just don't think it's worth maintaining this and instead we should work with upstream.

**Comment by Fantu** [comment]
@ItzSwirlz: as nemo-gtkhash is already present in debian (https://packages.debian.org/buster/nemo-gtkhash), from gtkhash upstream source, so another packages for add mint fork is not needed (from a fast look I don't see important mint changes https://github.com/linuxmint/nemo-extensions/commits/master/nemo-gtkhash), is not at latest version (latest update was 2 years ago), so can be useful ask if maintainer need help (if you want)

**Comment by Salamandar** [comment]
I'm closing this PR and working upstream (https://github.com/tristanheaven/gtkhash/pull/116)

**Comment by Salamandar** [comment]
The official gtkhash project merged Meson. That may be a plan to remove the "fork" maintained here ?

**Comment by ItzSwirlz** [comment]
Yeah at this point idk what we are waiting for

**Comment by Fantu** [comment]
I also think that this fork of gtkhash should be removed, the upstream one is more supported and maintain this without a good reason seems a waste of time and probably less features and more bugs for mint users, from a fast look don't seems there are mint changes needed (and missed upstream) but if there are can be easy done a PR upstream.
@clefebvre what do you think?

**Comment by clefebvre** [comment]
Yes, I'm OK with this.

**Pull request closed without merging**
