### PR TITLE
Meson

### PR DESCRIPTION
**Pull request by Salamandar**
This replaces #294 because the working repo was deleted since then.

### CODE REVIEW

**Review by ItzSwirlz — CHANGES_REQUESTED** [review]
nemo-gtkhash: Meson with polarssl/mbedtls: I think you need to add a dependency check for this, because if mbedtls-dev isn't installed it will complain the header doesn't exist instead of saying the library dev headers doesn't exist like it would with nettle/gcrypt/libcrypto/nss

**Comment by ItzSwirlz** [comment]
nemo-gtkhash build fail on Ubuntu Hirsute arm64:
```
ninja: Entering directory `build'
[11/27] Compiling C object src/hash/libhash.a.p/hash-lib-crypto.c.o
FAILED: src/hash/libhash.a.p/hash-lib-crypto.c.o 
cc -Isrc/hash/libhash.a.p -Isrc/hash -I../src/hash -I. -I.. -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/nss -I/usr/include/nspr -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g '-DG_LOG_DOMAIN="nemo-gtkhash"' -DHAVE_CONFIG_H -fPIC -DIN_HASH_LIB -MD -MQ src/hash/libhash.a.p/hash-lib-crypto.c.o -MF src/hash/libhash.a.p/hash-lib-crypto.c.o.d -o src/hash/libhash.a.p/hash-lib-crypto.c.o -c ../src/hash/hash-lib-crypto.c
../src/hash/hash-lib-crypto.c:37:13: error: field ‘ctx’ has incomplete type
   37 |  EVP_MD_CTX ctx;
      |             ^~~
../src/hash/hash-lib-crypto.c: In function ‘gtkhash_hash_lib_crypto_get_md’:
../src/hash/hash-lib-crypto.c:48:11: warning: implicit declaration of function ‘EVP_sha’; did you mean ‘EVP_sha1’? [-Wimplicit-function-declaration]
   48 |    return EVP_sha();
      |           ^~~~~~~
      |           EVP_sha1
../src/hash/hash-lib-crypto.c:48:11: warning: returning ‘int’ from a function with return type ‘const EVP_MD *’ {aka ‘const struct evp_md_st *’} makes pointer from integer without a cast [-Wint-conversion]
   48 |    return EVP_sha();
      |           ^~~~~~~~~
../src/hash/hash-lib-crypto.c:54:11: warning: implicit declaration of function ‘EVP_mdc2’; did you mean ‘EVP_md5’? [-Wimplicit-function-declaration]
   54 |    return EVP_mdc2();
      |           ^~~~~~~~
      |           EVP_md5
../src/hash/hash-lib-crypto.c:54:11: warning: returning ‘int’ from a function with return type ‘const EVP_MD *’ {aka ‘const struct evp_md_st *’} makes pointer from integer without a cast [-Wint-conversion]
   54 |    return EVP_mdc2();
      |           ^~~~~~~~~~
../src/hash/hash-lib-crypto.c: In function ‘gtkhash_hash_lib_crypto_is_supported’:
../src/hash/hash-lib-crypto.c:74:2: warning: implicit declaration of function ‘EVP_MD_CTX_cleanup’; did you mean ‘EVP_MD_CTX_create’? [-Wimplicit-function-declaration]
   74 |  EVP_MD_CTX_cleanup(&data.ctx);
      |  ^~~~~~~~~~~~~~~~~~
      |  EVP_MD_CTX_create
../src/hash/hash-lib-crypto.c:64:27: warning: variable ‘data’ set but not used [-Wunused-but-set-variable]
   64 |  struct hash_lib_crypto_s data;
      |                           ^~~~
[16/27] Compiling C object src/hash/libhash.a.p/hash-lib-nss.c.o
ninja: build stopped: subcommand failed.
```
^ not a meson thing but something to deal with later

**Comment by ItzSwirlz** [comment]
nemo-seahorse arm64 hirsute:
```
[18/21] Compiling C object tool/nemo-seahorse-tool.p/seahorse-util.c.o
FAILED: tool/nemo-seahorse-tool.p/seahorse-util.c.o 
cc -Itool/nemo-seahorse-tool.p -Itool -I../tool -I. -I.. -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/aarch64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/gcr-3 -I/usr/include/gck-1 -I/usr/include/p11-kit-1 -I/usr/include/libcryptui -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -DHAVE_CONFIG_H -pthread -MD -MQ tool/nemo-seahorse-tool.p/seahorse-util.c.o -MF tool/nemo-seahorse-tool.p/seahorse-util.c.o.d -o tool/nemo-seahorse-tool.p/seahorse-util.c.o -c ../tool/seahorse-util.c
../tool/seahorse-util.c:37:10: fatal error: avahi-glib/glib-watch.h: No such file or directory
   37 | #include <avahi-glib/glib-watch.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[19/21] Compiling C object tool/nemo-seahorse-tool.p/seahorse-widget.c.o
../tool/seahorse-widget.c: In function ‘object_finalize’:
../tool/seahorse-widget.c:179:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  179 |     if (seahorse_widget_get_widget (swidget, swidget->name))
      |     ^~
../tool/seahorse-widget.c:182:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  182 |  g_object_unref (swidget->gtkbuilder);
      |  ^~~~~~~~~~~~~~
[20/21] Compiling C object tool/nemo-seahorse-tool.p/seahorse-vfs-data.c.o
ninja: build stopped: subcommand failed.
``` dep check needed for avahi-glib probably (or mostl ikely)

**Comment by Salamandar** [comment]
> nemo-gtkhash: Meson with polarssl/mbedtls: I think you need to add a dependency check for this, because if mbedtls-dev isn't installed it will complain the header doesn't exist instead of saying the library dev headers doesn't exist like it would with nettle/gcrypt/libcrypto/nss

I don't understand. I check for those headers :

```
if get_option('mbedtls')
    mbedtls_version = -1

    mbedtls = cc.find_library('mbedcrypto', has_headers: 'mbedtls/md.h', required: false)
    if mbedtls.found()
        mbedtls_version = 2
    else
        mbedtls = cc.find_library('polarssl', has_headers: 'polarssl/md.h')
        if mbedtls.found()
            mbedtls_version = 1
        endif
    endif

    if mbedtls_version == -1
        error('Could not find mbedtls or polarssl !')
    endif
else
    mbedtls = no_dep
endif
```

**Comment by Salamandar** [comment]
> nemo-gtkhash build fail on Ubuntu Hirsute arm64:

Yeah. Same with Autotools. Can't understand the issue.

**Comment by Salamandar** [comment]
The Avahi issue should be fixed now. Sharing was not enabled with Autotools ;)

**Comment by Salamandar** [comment]
I disabled GTKHash because it was giving a hard time.
Everything now builds.

**Comment by ItzSwirlz** [comment]
Seems good :) (I couldn't test nemo-preview as on Ubuntu xreader isn't packaged, but it's probably good)

**Comment by mtwebster** [comment]
Hi, I've found meld handy for checking autotools->meson consistency, so I built all of nemo-extensions pre- and post-meson and compared the package dirs in ./debian - there are just a few things that come out different, otherwise it all looked really good:

dropbox - icon missing:
image

repairer - folder name changed:
image

seahorse - "Name" fields in the desktop files not being put in the generated file - those are the only fields with an underscore (`_Name`) - that may not be necessary anymore I think.
image

nemo-share - no translations installed:
image

**Comment by Salamandar** [comment]
Thanks !! I'm handling that soon.

**Comment by Salamandar** [comment]
> nemo-filename-repairer - folder name changed:
> nemo-share - no translations installed:

Should be fixed now.

> dropbox - icon missing:

Erf, I installed it into `$prefix/share/icons/nemo-dropbox`. Fixed now.

> seahorse - "Name" fields in the desktop files not being put in the generated file - those are the only fields with an underscore (_Name) - that may not be necessary anymore I think.

That's a gettext issue. I'll work on that.

**Comment by ItzSwirlz** [comment]
> repairer - folder name changed:

It really should be. The package name is nemo-filename-repairer, it's in the LM repo.

**Comment by Salamandar** [comment]
>  seahorse - "Name" fields in the desktop files not being put in the generated file - those are the only fields with an underscore (_Name) - that may not be necessary anymore I think.

Fixed too ! All done :)

**Comment by mtwebster** [comment]
Can you rebase this? Looks good otherwise.

It's a simple fix, it's stumbling on this change: https://github.com/linuxmint/nemo-extensions/commit/6e80a2bd55a22666dedf930265687291c244d1c5

Thanks

**Comment by ItzSwirlz** [comment]
Sorry. I thought that after I did it was when he was still working on it so yeah... my bad.

**Comment by Salamandar** [comment]
I'm going to rebase. But are you OK with this PR deleting Autotools completely ?

**Comment by mtwebster** [comment]
Yes definitely - any regressions that pop up we'll just fix in meson.  There's no way I'd go back to autotools :)

**Comment by mtwebster** [comment]
Thanks a lot

**Comment by ItzSwirlz** [comment]
Only worry would be MATE, I think they still like Autotools but have optional meson support

**Pull request merged**
