### PR TITLE
[WIP] audio-tag, ffmpeg vs mutagen => more supported formats

### PR DESCRIPTION
**Pull request by robinechuca**
Hello, I made this small modification which corrects the following points:
- Support for many more formats (including video formats like avi, mkv, mp4 ...)
- Added the number of channels (mono, stereo, ...)
- Dynamic tag display for more flexibility in formats other than mp3

### CODE REVIEW

**Comment by robinechuca** [comment]
For the depandances, you have to use the ffmpeg module but installed with pip (pip install ffmpeg-python). I don't know how to integrate this?

**Comment by robinechuca** [comment]
For the depandances, you have to use the ffmpeg module but installed with pip (pip install ffmpeg-python). I don't know how to integrate this?

**Comment by Fantu** [comment]
python3-ffmpeg (source ffmpeg-python) seems missed on debian (and ubuntu) repository
an RFP on debian should be open (https://wiki.debian.org/RFP), the upstream project is https://github.com/kkroening/ffmpeg-python, I don't have time to package it (I'm busy on too many things) but if you're having trouble creating RFP tell me and I'll create it

**Comment by robinechuca** [comment]
I am a very bad programmer out of python! Making an RFP package is out of my reach. I added 6 lines of code from the 'python-ffmpeg' module that allow me to do without this module. This is the simplest I can do.

**Comment by robinechuca** [comment]
Is there anything to change or is the pull request satisfactory as it is?

**Comment by Fantu** [comment]
I checked only the packaging part and not review all the code, about approve and merge it only mint team people like clem and mtwebster can do it

**Comment by robinechuca** [comment]
I see that none of the 4 pull requests have been merged. Are the developers aware that there are pull requests? How can we inform them?

**Comment by mtwebster** [comment]
Hi,

I like the added support for more formats, but mp3 support seems to have regressed, at least in its presentation:

Currently:
master-mp3

This PR:
pr-mp3

Other wise I think this is fine.

Thanks

**Comment by robinechuca** [comment]
Hi,

Regarding the formatting, I don't know how to make it dynamic. So I chose a more general presentation that sticks with all formats.
Regarding MP3 content, on the contrary, it has progressed. All the previous fields are still present. We notice that "album artist" works and above all it adapts. In the sense that it is based on ffmpeg which is maintained. If a format changes, a field is added or a file contains a personalized tag, it appears here.
I'm not sure I understand the term regress? You mean the new way of presenting data is uglier?

**Pull request closed without merging**
