### PR TITLE
Samba improvements

### PR DESCRIPTION
**Pull request by clefebvre**
This PR addresses some of the samba related issues described in https://github.com/linuxmint/linuxmint/issues/125.

### CODE REVIEW

**Comment by griga-upjs** [comment]
Hello! I just read about automatic firewall rules after Samba installation. I think it is definitely a bad idea - it is similar like in MS Windows environment. People loose the ultimate ability to control firewall, which is one of the basic aspects of security in networks.

If you want to help people with adding firewall rules, the best idea would be to ask user first, if he want to add default firewall rules and let him choose to not add rules at all, if he do not want to.

**Comment by clefebvre** [comment]
Hi,

People can configure the firewall, see and remove rules. We ship a graphical utility for this.

Samba does not work without these rules. This is a functional requirement for what the user asked already. The assumption here is that we do what we're asked and that when we're done, it works.

Now, with that said, I think you have a point. We should mention the fact that we're adding rules. Yes, they are needed. Yes, they are easy to remove. Still, we should mention them so the user is aware of what was done on his behalf. We already explain we're installing samba and adding his account to a group, we can certainly mention that as well.

We'll get this changed for the next version.

**Comment by griga-upjs** [comment]
Very well. Thanks.

There is few problems. Not all those rules are really necessary for Samba. TCP 445 is enough. User may want to allow just specific IP address - in this situation, there will be opened ports listening to all incoming connections for a specific amount of time - this can be unwanted on some networks. Another thing is - user may have prepared specific rules before allowing directory sharing - adding another rules is unwanted in this situation. User may even want to try sharing on localhost - they need no rules then.

IMHO, if user is capable of turning UFW on (default is off, right?) and setting default policy, he should be capable to manage rules and think about it, if he plannig to do something like sharing directories. Firewall is not part of sharing - it is another layer used for filtering packets, mainly for security purposes - if the rules are managed automatically, without knowledge of what was done, the firewall is useless then. And we will find ourselves in the firewall-hell situation like in MS Windows.

Think about another thing - when user enable directory sharing, the Samba is installed, some privileges stuff are done and firewall rules are added. What about if user remove last directory share? Will be Samba uninstalled and firewall rules removed? What is the best way to do this? Maybe Samba preinstalled (but disabled by default - it will be enabled with creation of first share and disabled again after last share removal) and firewall disabled by default (no rules adding are necessary). Or maybe (opt-in) checkbox with "Add firewall rules" (accessible only when ufw is enabled) within sharing configuration dialog (firewall can be enabled by default then)?

I understand, that Mint is desktop distro, which should be as easy to use as possible, but it should be stable and secure and every user experience improvement should be done with security in mind. Do not forget, that users often do not understand to what are they doing, what are they demanding and doesn't think with security in mind - it is distributor's endeavor to do things in a secure manner. Yes - maybe not everybody will like what you have done, but you will definitely lose more users when Mint will be considered as a "system which spontaneously opening ports", then if it will have a reputation as a system "with security in mind". Think about it, because notice (with warning about adding firewall rules) is the least, what have to be done.

**Comment by leigh123linux** [comment]
@clefebvre Is it possible to limit the UFW rule to ethernet adaptors only, imagine using those setting when visiting an internet cafe without passworded samba :-)

**Comment by griga-upjs** [comment]
@leigh123linux Or maybe use UFW ruleset profiles for this reason. It is not so easy to do it automatically in right manner because there are lots of individual requirements / options. That is why I would prefer not to touch to firewall at all or simply make it like opt-in option with big red warning.

**Pull request merged**
