### PR TITLE
[WIP] Modify tortoisehg-nautilus extension for nemo

### PR DESCRIPTION
**Pull request by jimtremblay**
Adapt tortoisehg-nautilus version 2.10-1 extension for Nemo File Manager.

### CODE REVIEW

**Comment by grizzlyfred** [comment]
I wished it worked. I somehow managed to get a recent 3.3.2 mercurial and tortoisehg running (the mercurial ppa on lp has not been updated for a year). I have the icons in nautilus now, but replacing "nemo" for "nautilus" and copying the file as a nemo extension did nothing for me, sadly.

**Comment by grizzlyfred** [comment]
I made it misterously work. I have added skeleton control- and other files to support packaging in my fork. The fine tuning is unknown to me, so if it were pulled and adjusted so that it would fit the rest of the extensions... Shall I create a separate pull request or wait if something happens in the OPs fork?

**Comment by GLolol** [comment]
I could probably Debianize it using https://github.com/linuxmint/nemo-extensions/tree/master/nemo-rabbitvcs/debian as a guide.

**Comment by GLolol** [comment]
And done.... (I didn't see @grizzlyfred's [pull request](https://github.com/jimtremblay/nemo-extensions/pull/1) until AFTER I made the package :\ )

**Comment by grizzlyfred** [comment]
After the update to 17.2 I was almost stuck again: on launchpad, mercurial 3.3.3 is available, and a tortoisehg 3.3.2 which don't install together. So I built mercurial 3.4.2 from source and hg cloned (as recommended) the tortoisehg. After fixing depency issues with qt4 and whatnot, it installed file. Even the extension in nemo is partially working (i.e. the overlays are there). But I have no idea how to handle this error:

(nemo:8536): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_export: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
Initializing folder-color-switcher extension...
icon not found menuclone.ico
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/nemo-thg.py", line 215, in get_background_items
    return self.buildMenu([vfs_file], True)
  File "/usr/share/nemo-python/extensions/nemo-thg.py", line 174, in buildMenu
    return self._buildMenu(menus)
  File "/usr/share/nemo-python/extensions/nemo-thg.py", line 195, in _buildMenu
    for subitem in self._buildMenu(menu_info.get_menus()):
  File "/usr/share/nemo-python/extensions/nemo-thg.py", line 206, in _buildMenu
    self.icon(menu_info.icon))
TypeError: Argument 3 does not allow None as a value

so some menuclone.ico is not found (probably for cloning repos... where would I have to put that one? As I do have the status overlay icons, I guess I have to figure out where the menu icons should reside, they were probably removed, when I removed the broken .debs from the launchpad ppa...

**Comment by CreamyCookie** [comment]
Any news on this? Could you maybe update your clone and then try if the error still persists?

**Comment by grizzlyfred** [comment]
I am on Mint 17.3 now, eagerly awaiting 18 ;-). For most of the times, the extension works, but I do not really remember what I had to do to get it working... I would opt for "never touch a running system" but the underlying Ubuntu 14.04-Base shows its outdatedness in every corner, even with the wily kernel: 

Right now I am adapting a new setup on a 2014 laptop that used to be running Ubuntu 14.04  and rather than updating that one, I'm trying out Manjaro Cinnamon right now (played nice in the past year in a virtual machine, was always up to date and "rolling" and really "snappy") and have to go through the same process to set up the original nautilus extension for nemo. Not sure if I have it yet installed, as I only installed tortoisehg from AUR via yaourt... So I will pull-merge what is there now and see how I get along...

**Comment by grizzlyfred** [comment]
On the 16.06 manjaro install with recent tortoisehg 3.8.3 the simple copying of the nemo-thg.py to the global location (that needed to be created, as mentioned in the readme) it just worked, overlays and context menu. So all the trouble is to ubuntu base being outdated and the thg ppa also.
For the debian packaging - it remains to check whether the GPL version is OK, and whether or not to provide the contributor's emails.

**Comment by grizzlyfred** [comment]
I had immense trouble dist-upgrading to mint 18. In consequence I rolled back my btrfs-based install to mint 17.3 and am now trying to get a setup via virtualbox and a vmdk file do a new system disk which I can later boot into once all is running...

In Mint 18 - as with manjaro cinnamon - simply copying the `nemo-thg.py` to `/usr/share/nemo-python/extensions/` and restarting `nemo -q` is sufficient to have the overlays and context menu entries.

nemo-python does not exist therefore I remove it from the install instructions for mint 18+.
From my point of view, that is working when simply copying jim tremblays script to the proper location - so I am giving him a pull request in hope his state will be pulled into the master and thus sooner or later automatically be available.

**Comment by grizzlyfred** [comment]
Refer also to #171

**Pull request closed without merging**
