### PR TITLE
Fix .gitignore for builds

### PR DESCRIPTION
**Pull request by rcalixte**

### CODE REVIEW

**Comment by mtwebster** [comment]
Could you add the other generated files?

these:
```
       nemo-audio-tab/nemo-audio-tab-build-deps_5.4.1_amd64.buildinfo
	nemo-audio-tab/nemo-audio-tab-build-deps_5.4.1_amd64.changes
	nemo-audio-tab_5.4.1.dsc
	nemo-audio-tab_5.4.1.tar.gz
	nemo-audio-tab_5.4.1_all.deb
	nemo-audio-tab_5.4.1_amd64.buildinfo
	nemo-audio-tab_5.4.1_amd64.changes
	nemo-compare/nemo-compare-build-deps_5.4.1_amd64.buildinfo
	nemo-compare/nemo-compare-build-deps_5.4.1_amd64.changes
	nemo-compare_5.4.1.dsc
	nemo-compare_5.4.1.tar.gz
	nemo-compare_5.4.1_all.deb
...
...
```
I'm pretty sure gitignore always recurses - I don't think you'll need to glob the parent dirs, just the filenames.


Thanks

**Comment by rcalixte** [comment]
> I'm pretty sure gitignore always recurses - I don't think you'll need to glob the parent dirs, just the filenames.
That's correct, I'll patch this up. Apologies!

**Comment by rcalixte** [comment]
@mtwebster I thought about globbing the package directories with `nemo-*/debian/nemo-*` but opted not to. I'm fine either way but this should be good to go. Thanks!

**Comment by mtwebster** [comment]
Ack sorry, one more:
```
[08:59:36 AM] mtwebster@mintbox3:~/bin/nemo-extensions[gitignore %]> git status -u
On branch gitignore
Your branch is up to date with 'origin/pr/455'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	nemo-dropbox-dbgsym_5.4.1_amd64.ddeb
	nemo-filename-repairer-dbgsym_5.4.1_amd64.ddeb
	nemo-fileroller-dbgsym_5.4.1_amd64.ddeb
	nemo-image-converter-dbgsym_5.4.1_amd64.ddeb
	nemo-preview-dbgsym_5.4.1_amd64.ddeb
	nemo-seahorse-dbgsym_5.4.1_amd64.ddeb
	nemo-share-dbgsym_5.4.1_amd64.ddeb

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by rcalixte** [comment]
Apologies for the oversight on my part. We should be good to go!

**Comment by mtwebster** [comment]
Thanks - no worries, I always forget them too, not sure why they felt the need for a new extension.

**Pull request merged**
