### PR TITLE
nemo-dropbox: PEP 394 support

### PR DESCRIPTION
**Pull request by eli-schwartz**
This is explicitly python2 and should use the corresponding versioned path.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
lol, overlaps with #341, should've submitted this a year ago.

At least it is less opinionated and therefore, potentially, easier to merge. But feel free to close it if the other PR gets merged.

**Comment by leigh123linux** [comment]
Arch has no use for this, see

https://aur.archlinux.org/cgit/aur.git/tree/01__Remove-python-dependencies.patch?h=nemo-dropbox

**Comment by eli-schwartz** [comment]
- I am not the maintainer of that PKGBUILD, so I don't know what it does
- removing it entirely from this repository is surely an option to be considered, but if so, it should happen upstream, not in downstream build scripts
- this is generally useful for other downstream packagers as well, especially as we move closer to 1/1/2020. https://fedoraproject.org/wiki/FinalizingFedoraSwitchtoPython3#Other_Linux_Distributions_and_OSes

I *might* add the dropbox extension to my official, non-AUR package. If I did, I would want it to not require patches in order to work properly.

**Comment by mtwebster** [comment]
We can merge this for now, I will look a bit more if there's any reason not to do 341

**Pull request merged**
