### PR TITLE
[WIP] Port to named icons/labels instead of GtkStock

### PR DESCRIPTION
**Pull request by ItzSwirlz**
(i need to test this to ensure i didn't mess anything up)

### CODE REVIEW

**Comment by icarter09** [comment]
Could you also rename this to a "WIP" in case no one sees that it is a draft? Thanks.

**Comment by JosephMcc** [comment]
I'm going to make a suggestion here. Don't submit PR's that are completely untested. Wait until you've tested them and mostly made sure they work before submitting them. It's frustrating on our side to see a PR and you either say or it's clear that it's untested.

**Comment by mtwebster** [comment]
I don't mind fixing the icon names, but there's absolutely no reason to create new translations for us when the stock ones work just fine. They're deprecated but they're also not going anywhere either. When and if (that's a big if) we ever move to gtk4, we can deal with it.

So:
Icon names - fine.
Button labels - leave them alone.

**Comment by JosephMcc** [comment]
I have no issue with the PR or what it's doing at all. But you have submitted PR's in the past that wouldn't even build and you say right out this is untested. That means you are putting the onus on others and their time to find that out the hard way. What I'm asking is that you do your best to make sure these actually work before you ask other's to dedicate their time to reviewing them.

**Comment by mtwebster** [comment]
Ok after some discussion, it's ok to leave the new translations in.

**Comment by ItzSwirlz** [comment]
> So:
> Icon names - fine.
> Button labels - leave them alone.

My personal ideas was more begin making meson build options to build with GTK4 for upstream maintainers, if they wish so try to make it compatible but if it's only going to make things worse then I wouldn't suggest. I would think we would all agree.

**Comment by ItzSwirlz** [comment]
> But you have submitted PR's in the past that wouldn't even build and you say right out this is untested.

It's not your responsibility-it's mine.

**Pull request closed without merging**
