### PR TITLE
[WIP] add, fix, update croatain translations

### PR DESCRIPTION
**Pull request by muzena**

### CODE REVIEW

**Comment by monsta** [comment]
This PR modifies a lot of unrelated translation files. Please recheck it.

**Comment by muzena** [comment]
Now I only add and update hr.po files, and add hr strings to .desktop files

**Comment by monsta** [comment]
Looks ok, but I've talked to @clefebvre about this PR, and some questions were raised...

- please don't modify ```GenericName```'s here - if you wish to do so, make a separate PR for that (and add some explanations).
- is ```nemo-compare/po/POTFILES.in``` really needed?
- ```nemo-pastebin/debian/nemo-pastebin.debhelper.log``` is already removed in the current git master, no need for that.

**Comment by muzena** [comment]
POTFILES.in I used it for generating/updating pot file, "intltool-update --report"
I forgot it to remove.

**Comment by muzena** [comment]
I fix GenericName and remove POTFILES.in.

**Comment by clefebvre** [comment]
Hi,

You're still modifying 

GenericName=Nemo Pastebin configuration panel

That no longer matches the msgid.

**Comment by muzena** [comment]
Fixed GenericName

**Comment by monsta** [comment]
@clefebvre: looks ok for merging now.

**Comment by muzena** [comment]
@clefebvre please can you merge this to be available in new Linux mint release.

**Comment by clefebvre** [comment]
Hi,

Why add [hr] name/comment to desktop files where they don't contain any other locale?

I'm sorry this is taking so long, but I'd rather not take any chances. Especially prior to release.

Addition of hr.po looks fine, adding hr to LINGUAS and list of locales looks fine too.

**Comment by muzena** [comment]
@clefebvre 
I add [hr] name/comment to desktop files to be shortcuts name/comment translate in Menu like in screenshot below, if it's so problem I will remove this few string from desktop files.
menu1

**Comment by clefebvre** [comment]
Hi,

Please don't modify the .desktop files.

Everything else looks good.

**Comment by muzena** [comment]
Hi @clefebvre, fixed .desktop files.

**Comment by monsta** [comment]
End of a long story :smile:

**Pull request merged**
