### PR TITLE
Remove buildall, rewrite build (make use of build-order), clenup makepot, cleanup circleci config.

### PR DESCRIPTION
**Pull request by Salamandar**
* `buildall` and `build` are duplicates (almost), and they could be used in the CI scripts. I cleaned up all that.
  * They now use the `build-order` file instead of a glob.
* Cleanup makepot (regroup list of files, call xgettext only 3 times)
* Cleanup CircleCI config : use conditional instead of bash test. Use `buildall` script.

### CODE REVIEW

**Comment by mtwebster** [comment]
- Can you leave buildall or any sort of mechanism to build all of the extensions from a terminal?
- Don't run makepot, clem does this before tagging the next major release.

**Comment by Salamandar** [comment]
> Can you leave buildall or any sort of mechanism to build all of the extensions from a terminal?

Well, `build` and `buildall` were doing the same job, just differently. That's why I removed one of them. I can keep `buildall` instead of `build` though :)

**Comment by mtwebster** [comment]
nemo-extensions.pot is modified, so makepot was run - 

The 'build' script builds one specific extension, The buildall script does them all - I don't care about the single one, but I'd like to keep a command to build them all at once.

**Comment by Salamandar** [comment]
@mtwebster I revamped the scripts a bit :
* `build` can take N arguments that are names of extensions to build.
* If no argument is passed, it reads the `build-order` file to build all the extensions.

**Pull request merged**
