### PR TITLE
[WIP] Port Python extensions to Python 3

### PR DESCRIPTION
**Pull request by EduardDopler**
As Python 2 _will_ be discontinued and I don't want to see nemo-extensions depend on that gray version after end-of-support, I ported all Python scripts to the new version. For the source package of `nemo-python` the minimum version is 3.3 now which is supported since around Ubuntu Quantal/Raring, Debian Jessie and in all supported Fedora versions. The extensions are satisfied with Python 3.0 or 3.1.

Many extensions were in bad shape concerning programming standards, conventions and documentation. As we know, this makes it hard to maintain software and introduce new features or fix bugs without introducing new bugs e.g. due to unknown side effects.  Moreover, by cleaning up the code and simplifying it where possible, performance issues were addressed as the old code often made unnecessary checks, loops or system calls.

Details on the changes can be found in the corresponding commit messages. Here are the most prominent ones:

**nemo-compare**: f66d179 bea81f0
- total cleanup, new preference tool, less error-prone

**nemo-dropbox**: 744da22
- almost no changes (2500 lines of dirty mystery code)

**nemo-emblems**: 603c8d0
- total cleanup, better performance
- fixes bug which passed changes of multiple emblem property pages only to the most recently opened one

**nemo-folder-color-switcher**: e7f20ae e921dd9
- included in this repository (see below)
- total cleanup, better performance

**nemo-metadata-columns**: 722f809 cf6d1f8 d3308bb 25a3d9f
- new extension (replaces nemo-media-columns)
- more tags, simpler lookups, translated tag values, logically combined
  values

**nemo-metadata-tab**: 60fe0e2 fd7d7c7 cf6d1f8 d3308bb 25a3d9f
- new extension (replaces nemo-audio-tab)
- more file types (audio, video, image, PDF)
- all printable tags are read, the most important ones are displayed by default, the other ones are behind an expander
- translated tag values, cover art for audio files (ID3 and FLAC)
- image evaluation can be toggled in-code (as nemo has parts of that built-in)

**nemo-pastebin**: bd3f90f
- less error-prone, new preference tool, more options, watches config file automatically
- notifications are now essential, providing feedback throughout the process
- added actions to the notifications ("Copy URL to clipboard", "Open in browser")

**nemo-terminal**: 4dfe557
- minor cleanup
- introduced translations

**nemo-rabbitvcs**:
- removed due to major incompatibilities (both frontend and backend cannot be ported to Python 3, plus, it seems to produce many issues anyway. RIP.)
- I have a nemo-git extention on my personal TODO list.
- Initial work for visual git feedback is now (Jan 8 2016) introduced in daf3705.

---

As mentioned, (nemo-)`folder-color-switcher` was imported into this repository since it seems to belong here. All `caja` parts were removed (there is a `caja-extensions` repository for that).

In addition to the changes listed above all build files received updates and follow a mostly consistent style now. E.g. all Python extensions use `pybuild`, all C extensions provide the same `autoconf` layout in their `configure.ac` files. Besides, some deprecation warnings during the build process were addressed; some translation files have updated line references. Henceforth all refactored extensions present proper README files. Important changes for each extension are mentioned in `*/debian/changelog`.

All extensions are tested with Linux Mint 17.2 and 17.3 and work flawlessly for several weeks.

This commit closes or resolves the following GitHub issues (or makes them obsolete):
- closes linuxmint/nemo-extensions#139
- closes linuxmint/nemo-extensions#134
- closes linuxmint/nemo-extensions#131
- closes linuxmint/nemo-extensions#128
- closes linuxmint/nemo-extensions#127
- closes linuxmint/nemo-extensions#125
- closes linuxmint/nemo-extensions#109
- closes linuxmint/nemo-extensions#93
- closes linuxmint/nemo-extensions#58
- closes linuxmint/nemo-extensions#46
- closes linuxmint/nemo-extensions#25
- closes linuxmint/nemo-extensions#23
- closes linuxmint/nemo-extensions#18

### CODE REVIEW

**Comment by GLolol** [comment]
Why are there so many extra commits (e.g. the Initial commit one)?

**Comment by EduardDopler** [comment]
As the message states, I included the nemo-extension `folder-color-switcher` into `nemo-extensions`. IMHO it belongs here.
And in order to keep the git history, I merged it, hence all its commits are preserved and accessable.

**Comment by muzena** [comment]
@EduardDopler 
I build .debs in my PC and install nemo extensions, python3 extensions don't work, there is no i Nemo e.g. nemo-metadata-columns, nemo-metadata-tab.
And why I can't build debs in launchpad?
See buildlog:
https://launchpadlibrarian.net/230719113/buildlog_ubuntu-trusty-amd64.nemo-python_3.0.4~trusty_BUILDING.txt.gz

**Comment by EduardDopler** [comment]
@muzena I didn't understand your sentence:
> there is no i Nemo e.g. nemo-metadata-columns, nemo-metadata-tab

Anyway, I updated a build file, maybe that will fix your build process?

**Comment by EduardDopler** [comment]
@muzena The problem with builds on Launchpad for this package is that Ubuntu trusty provides only an old version of `libnemo-extension-dev` but Mint does ship it (>=2.6.0).
If you set your build from trusty to xenial and use the new source version I just uploaded, it should build. See [my test build on Launchpad](https://launchpad.net/~garteneden/+archive/ubuntu/nemo-extensions/+packages) ("3.0.4").

**Comment by muzena** [comment]
@EduardDopler Thanks now it works.
libnemo-extension-dev but Mint does ship it (>=2.6.0) This isn't problem. You can add [cinnamon-nightly repository](https://launchpad.net/~gwendal-lebihan-dev/+archive/ubuntu/cinnamon-nightly) as build dependency.
Go to [your reposytory](https://launchpad.net/~garteneden/+archive/ubuntu/nemo-extensions/+packages) then click on "Edit PPA dependencies" options, copy    ppa:gwendal-lebihan-dev/cinnamon-nightly    to   Add PPA dependency: (Optional)  field and then click on save.
Now you can retry build nemo-python.

**Comment by EduardDopler** [comment]
In the latest commit I clarified some (build-) dependencies.
[My PPA](https://launchpad.net/~garteneden/+archive/ubuntu/nemo-extensions) lists all extensions now (for users of Ubuntu Wily and later due to the old version of `libnemo-extensions-dev` provided in Trusty's repository. Though this limitation does not apply for Mint users as we have 2.6.0 here available.)

@muzena No, I won't include nightly builds in a public PPA.

**Comment by muzena** [comment]
@EduardDopler I did a clean install of Linux Mint 17.3 and extensions from your repository, but some extensions don't work, I tried on mp3 song to see in tab properties audio information but there's no audio info tab, also Nemo terminal don't work. All extension you port to python3 don't work.
Maybe missing some dependencies?

**Comment by EduardDopler** [comment]
@muzena Okay, thank you for you feedback. I located the problem. It comes down to the way Ubuntu installs Python3 versions (they have the "m" suffix sometimes) and how multiarch environments are considered right now. Anyway, I already found a solution and will commit it in the next days... :christmas_tree:

**Comment by EduardDopler** [comment]
@muzena Fixed (hopefully).

**Comment by muzena** [comment]
@EduardDopler  Still don't work, and nemo-preview now has unresolved dependencies, older versions in trusty repository;  libgstreamer1.0-0 (>=1.4.0)   libmusicbrainz5-2 (>=5.1.0+git20150707)

**Comment by EduardDopler** [comment]
﻿@muzena The problem is the PPA. As these packages won't build on native Ubuntu trusty (due to the old versions of nemo and others), I had to choose Ubuntu wily as the minimum version. But wily includes its own versions of the dependent packages which aren't in Linux Mint 17.x repositories. So the packages built there on Launchpad are really only for Ubuntu users (wily and xenial).
But as a Mint 17.2+ user you do have all packages in your OS installed. You just need to build them yourself—or wait until someone includes my pull request into an official Mint repo (for Mint 18).

Building them yourself is really easy. Just `cd` into the nemo-python directory and run `dpkg-buildpackage`. Repeat that for every extension you want to install. In the parent directory you will find all DEB files.

**Comment by muzena** [comment]
@EduardDopler Works good, I tried various video, audio format and pdf, all formats are worked, only on mp3 this two [mp3 file samples](https://mega.nz/#!GwNghDZD!oy5JH1-3_nwwltgBNFUiMTJoW7lZtLT0smjDjonf_8E) 
1. Röyksopp - What Else Is There (HD)  - has audio tab
2. Lipe Cvatu,Sve Je Isto K'o I Lani - has no audio tab

**Comment by EduardDopler** [comment]
I'm glad, it worked.
I looked into your samples. The second one seems to have broken ID3 tas, at least that's what EasyTAG tells me. After correcting it with that tool, also the audio tab appears. But still that's not good behavior of my extension, I must admin. I'll look into that after the holidays.

**Comment by muzena** [comment]
@EduardDopler Can you port this extension to Nemo if it possible?
[nfs-lan](http://nfs-lan.sevka.info/)
[git-nfs-lan](https://github.com/sevka/nfs-lan)
[Feature Request](https://github.com/linuxmint/nemo-extensions/issues/71)

**Comment by EduardDopler** [comment]
@muzena I fixed the issue with broken cover art tags, the extension now just ignores such data but shows the rest (308d679).

Also, I updated my PPA. It should work now for both Linux Mint 17.2+ and Ubuntu *trusty*, *wily* and *xenial* systems. *Trusty* users still need an updated version of Nemo which they can obtain from another PPA I host there. I tried this installation method on an Ubuntu *trusty* system and it worked fine.

**Comment by muzena** [comment]
@EduardDopler nemo-compare extension don't work.

**Comment by EduardDopler** [comment]
@muzena Could you *please* describe what's not working? In what situations? Never? What is the error message when running nemo from terminal? What does the nemo-compare-preferences tool say?
I (on 17.3) and two other users (on 17.2 and trusty) use it day-by-day and it works fine for us.

**Comment by muzena** [comment]
eg. when I click left clik on some .txt file there is no in context menu Compare option, and click on nemo-compare-preferences tool in Menu does do anything, won't open preferences.
This is message from terminal:
mint@mint-asus ~ $ nemo
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/nemo-compare.py", line 79, in __init__
    self.config = cp_utils.NemoCompareConfig()
  File "/usr/share/nemo-compare/compare_utils.py", line 76, in __init__
    self.update_engines()
  File "/usr/share/nemo-compare/compare_utils.py", line 136, in update_engines
    config_engines = self.config[SECTION_ENGINES]
  File "/usr/lib/python3.4/configparser.py", line 937, in __getitem__
    raise KeyError(key)
KeyError: 'Engines'

**Comment by EduardDopler** [comment]
@muzena I cannot reproduce that. Are you on Mint? Could you try to delete the file `$HOME/.config/nemo-compare.conf` and run then `nemo-compare-preferences` from command line?

**Comment by muzena** [comment]
@EduardDopler Yes I use Linux Mint 17.3. I try to use on main Linux Mint which I upgraded from 17.1 --> 17.2 and now on --> 17.3 and on clean install of Linux Mint 17.3.
I delete $HOME/.config/nemo-compare.conf
This is terminal message:
mint@mint-asus ~ $ nemo-compare-preferences
Traceback (most recent call last):
  File "/usr/bin/nemo-compare-preferences", line 141, in <module>
    preferences = NemoCompareExtensionPreferences()
  File "/usr/bin/nemo-compare-preferences", line 67, in __init__
    self.config = cp_utils.NemoCompareConfig()
  File "/usr/share/nemo-compare/compare_utils.py", line 75, in __init__
    self.load()
  File "/usr/share/nemo-compare/compare_utils.py", line 125, in load
    return self.reset()
  File "/usr/share/nemo-compare/compare_utils.py", line 167, in reset
    config_engines[KEY_NWAY] = engines_installed[KEY_NWAY][0]
IndexError: list index out of range

**Comment by EduardDopler** [comment]
I see, the error appears when no n-way diff comparator engine is installed. I added diffuse to the dependencies, it should work now.
So @muzena either upgrade to the new version 3.0.2 or just install `diffuse` on your machine.
Thanks for reporting.

**Comment by muzena** [comment]
@EduardDopler 
Please, can you fix merge confilcts.

**Comment by EduardDopler** [comment]
Actually, I don't see any interest in continuing work for Linux Mint. I don't think that Mint developers show much respect to developers outside their core team and hence I decided to stop working on and even stop using Linux Mint.

**Comment by brownsr** [comment]
Eduard, it would be a shame to see you move on, that's a lot of work you have put in.  I write as a developer who like you has been pursuing an off-roadmap PR for an extended period (in my case a vertical panels PR for Cinnamon).  with no certainty of a merge at the end.  The team does work around the IRC dev channel rather than off a formal review of github PRs, so if you show up there and discuss your work when others are around hopefully you will get some positive feedback. I have had some helpful feedback and support when I have taken the initiative on IRC. I know the team have a strong preference for merging small changes rather than very large ones, so you might like to consider presenting your work in that matter.  Unfortunately mine is inherently rather large and monolithic ;-)

**Comment by clefebvre** [comment]
Hi,

+1 on what @brownsr said.

I just noticed your last comment today, it's hard to have eyes everywhere, but one place where things go much quicker is the IRC dev channel, definitely.

I've been following this PR for much longer and it scares me a bit because it's so big and because work was done prior to discussing important things... for instance RIP'ing some of the extensions, or merging the folder color switcher.

Anyway, I hope we'll discuss this for 3.2 and I hope we'll see you get closer rather than gone. I really enjoy seeing new people getting involved. I'm sorry you got the opposite impression. There's no real "core" team, there are devs with various degrees of involvement and presence.

**Comment by EduardDopler** [comment]
@clefebvre Thanks for your reply.
I write this from a developer's/software engineer's point of view and I try to leave out personal factors which led to my withdrawal from Linux Mint.

Firstly, I was in the IRC, at the time of development I've been there in UTC+2 from 8 am to 10 pm for weeks. Before I started, I asked for nemo-python and how it's invoked, you and mtwebster answered you don't know, so I figured it out myself and created [my first PR](https://github.com/linuxmint/nemo-extensions/pull/140) (you planned it for 3.0) which was of no use though, I found out later. That first PR had rather small changes but was useless because for any nemo-extension changing to Python 3 there has to be an underlying `nemo-python` supporting Python 3. So `nemo-python` had to be addressed: It had to be ported to Python 3. But, if you do so, it loses support for Python 2, which breaks any other extension. So the *only conclusion* was to port every extension.
I decided to do that, because no matter how your reaction would have been, if I'd complete my work and you wouldn't apply it to Mint, at least other users interested in that version would have been able to use my fork.
On the way, decisions had to be made. One of that was to include `folder-coler-switcher`, it just wouldn't have worked otherwise, because it also depends on `nemo-python`. Anyway, it just belongs here anyway, there is just no sense in keeping one extension in a different repo. [Let me add here that I cannot support having all extensions in just one repo at the first place. Throughout the porting process, I noticed how cumbersome it is to have many extensions with such different use cases, installation methods, tool sets, languages etc. in one place! Ideally, every extension should have its one repo here.]
Which leads me to my next point: Code quality. I know that you aren't accountable for that code as most parts weren't coded by you. But it was a total mess. It was ugly. Buggy, unreadable, had no consistency whatsoever. So, again, the only solution was to refactor the whole code, or at least where possible (`nemo-dropbox` was impossible to understand, for instance).

Let me summarize my points so far: The huge amount of code changes was inevitable. One change (extension) at a time was impossible and would have led to unsuable software.
And as we know from any Git etiquette: Don't publish commits breaking anything.

Talking about Git style. I really don't want to get personal. But your way of using Git(hub) is very obstructive for... anyone besides yourself. Or even for yourself. [Git rules](https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message) weren't agreed upon to annoy people but to help teams (and individuals) to understand each other's (your own) code and code history. And it's not only you, clem. Pick any Mint repo here and look at the commit history. It's just impossible to understand changes, fixes, features. Headings break into the next line, there is no infinitive, no summary and definitely no further description of hardly any commit. If you come in as someone new, you just can't see through what when why...... actually, I don't want to get into detail. I think you get my point. (In contrast you can review [any](https://github.com/linuxmint/nemo-extensions/pull/145/commits/cf6d1f8d2771ad50bdd3045ace75d2eb795adc17) [of](https://github.com/linuxmint/nemo-extensions/pull/145/commits/d7eba58f01c2112539e8e00d567898a2f0d2c8d1) [my](https://github.com/linuxmint/nemo-extensions/pull/145/commits/a794aff750db53064ceab361527fbe6c9e114723) [changes](https://github.com/linuxmint/nemo-extensions/pull/145/commits/d32b072dc93d925b3d5f92d65af2a037f5fc92c1) or even [outside](https://github.com/vurtun/nuklear/commits/master) [projects](https://github.com/google/FreeBuilder/commits/master) (picked randomly).

One more word on code quality: Python is easy, yes. It's great for many projects and perfect for Linux Mint tools. But the way it is used in many of your tools gives me the goosebumbps. I mean: What the heck is [this](https://github.com/linuxmint/Cinnamon/commit/fa0e8308ebf9ab3280d643c81844f1215cfeb856)? Or [this](https://github.com/linuxmint/mintupdate/blob/master/usr/lib/linuxmint/mintUpdate/checkAPT.py)? The first one is obvious, I guess, and the second one has many many faux pas, I could name 10 off the top of my head. Am I'm niggling? IMHO no, because bad software (as in buggy, insecure, slow, unportable etc) comes from bad code.

All told/nagged, I just don't think I am compatible with Mint's development style.

**Comment by clefebvre** [comment]
That's the thing, there's no such thing as Mint's development style, and if that's something important to you, then we need to talk about it.

I don't like XRevan's one-liner either, not to the point of telling him to modify it, but if it becomes an issue, we talk. I doubt he'd have an issue with that.

That merge in mintupdate is a manual merge for a PR which was done on the GTK2/python2 version of the tool. I had to fix a lot of conflicts and that's what you see here. I'm sorry it doesn't show up nicely in the git history. Maybe there's a better way to do it, and that's alright. Again, you can chat with me, point to me what I'm doing wrong and show me how to do it better. I'm happy to learn.

You worked like a horse on this, we talked very little. At the time I hadn't worked much on python3 either and I didn't really know the extent of what was involved here in nemo-extensions (which is a mess, I'll give you that).

**Comment by muzena** [comment]
@EduardDopler 
It is a pity you gave up development of nemo-extensions, I hope you'll change your mind and fix this conflicts for 3.2 version. The best feature is nemo-metadata-tab and nemo-metadata-columns, especially is usefule a view of detailed propertis of video files and photographs.

**Comment by brmmm3** [comment]
I'm wondering why this very interesting pull request isn't already merged? A switch to Python 3 is a good idea and the other improvements are also very interesting. Are there any plans to merge this? Are there any showstoppers?

**Comment by leigh123linux** [comment]
FYI python-2.7 will be supported to 2020

http://legacy.python.org/dev/peps/pep-0373/

@clefebvre  are you going to merge this in time for 3.2?

**Comment by muzena** [comment]
@EduardDopler 
Please can you fix this to be able to merge for 3.2, It missed me nemo-metadata-tab and nemo-metadata-tab features.

**Comment by EduardDopler** [comment]
Okay, I pulled all changes since version 3.0.0 and fixed all merge conflicts.
Github still complains about merge conflicts, maybe because I needed to cherry-pick and change some commits made in the meantime (December '15 until now). In my master branch everything worked out, all conflicts resolved, so I don't know what GH complains about...

**Comment by clefebvre** [comment]
Moving to Python 3 sounds good, the changes required to do it are pretty simple and represent just a few commits. These should be isolated from unrelated changes.

Before we do this though, I need to address what looks to me like the only show stopper to switching to Python 3. I see rabbitvcs-core only provides python 2 support. Are we ready to lose this extension?

Are there many people using it?

If anybody has concerns with the loss of this extension, please say so.

**Comment by leigh123linux** [comment]
@clem rabbitvcs provides the nemo extension 

https://github.com/rabbitvcs/rabbitvcs/commits/master 

rabbitvcs upstream seems pretty dead and bug riddled.

**Comment by EduardDopler** [comment]
@clefebvre The problem is that the old Python 2 scripts won't work with a `nemo-python` built against Python 3. So one would have to edit all old extensions in order to make them work semantically identical (this is not limited to only changing `print` to a function…). After that tedious work all bugs and shortcomings I found while refactoring or rewriting the extensions would still be existent. But as the files changed, the changes found in this PR could not be applied anymore; one would have to address all merge conflicts again.
If this is something* someone wants to do, he or she is very free to do so. But I won't.

**something= go back to current Python 2 state, apply changes only to nemo-python, then fix all 2to3-related bugs, test if all extensions work as expected, then fix build scripts (I updated a lot of them). At that state everything should work like it does now besides running on Py3 instead of Py2. Note though that I rewrote some extensions from scratch in a (hopefully) clean, documented, understandable and notably more efficient/faster manner. If you want that changes too, you'd have to extract my changes from this PR too and fix all merge conflicts coming from that new state.*

**Comment by clefebvre** [comment]
I fully understand that. After you put so much (way too much I would say) efforts into this, and mixed this huge variety of changes into a PR which I cannot merge, I am not asking you to produce more work. I'm thankful for what you've done, I'm sorry you did it the way you did and I'm not expecting you to split this into workable WIPs.

If some of these changes go through (and some should, whether we move to python 3 or not, that in itself really illustrates the need for modularity and isolation here), extra work will be required and I'm not suggesting that falls onto you.

**Comment by EduardDopler** [comment]
@clefebvre And I fully understand your point as a the LM maintainer. Maybe I wouldn't merge such a PR either. But—just to explain my decision back then—I felt that splitting the work into several PRs didn't make sense because, as I said, all depends on `nemo-python` and its Python version chosen there, i.e. if I ported nemo-python first without the extensions, the PR would have broken every extension. Same goes for the extensions themselves: Porting them without having an already ported nemo-python makes no sense. Hence I put everything together because that's what my perception of a Pull Request is in the end: It introduces something without breaking anything existent.
Anyway, I think we made our points.

**Comment by clefebvre** [comment]
We did.

And I kind of agree with you on putting extensions and extension-system into the same bag and thus the same PR. We sometimes split dependent PRs (and sometimes we have to, for instance when they affect distinct projects, that's often the case in Cinnamon for instance... a WIP affecting the settings daemon + some lib + the settings + the screensaver or whatever), and it's ok, as long as we get it all done during the cycle. It's not really an issue one way or another. Both approaches have their pros and cons.

What's more problematic is the merge of the folder switcher, the renaming/refactoring, the bug fixes, basically all the work you've put into that after/during the python 3 migration. I can't really have the ability to discuss them in isolation and reviewing them is much more complicated than reviewing the migration itself.

Other than the work you've done here, your comments and the situation we got ourselves into... all of this is also helping us. I do many different things within Linux Mint. The hardest part of my job is to turn down help or to refuse work that has already been done. It is not easy to listen to criticism but it is valuable.

You don't know this but your comments were discussed by many developers and this led to a very long discussion about style and best practices. Many disagreed about various things but we eventually decided to set up developer guidelines and put down on paper what felt important to many of us.

Today, I drafted a new section to list recommendations on pull requests. This document is very new and it can certainly get a lot better, but it's a start:

https://www.gitbook.com/book/linuxmint/developer-guidelines/details

So there you have it. It wasn't very pleasant, but I just wanted to show you. Some of your work might help implementing a potential move towards GTK3, but it's not just that. Your negative experience on this PR is helping us as well.

**Comment by EduardDopler** [comment]
Okay, thank you for your elaboration. I'm kind of glad I could help—even though in a different way I intended :beers:

**Comment by muzena** [comment]
And what now, does it would be merged in some future time?
@EduardDopler 
I install them, but they dosen't work well, maybe is missing some dependency.
nemo-metadata-tab on some multimedia files png jpg mkv avi mp3. there is no more tabs in properties,
nemo-metadata-columns eg. on video files Resolution FPS, aspect ratio... all is mostly unknown

**Comment by brmmm3** [comment]
And what if nemo-python would support both python versions? nemo-python could be
extended so that it detects via the first line in the python file if it is for
Python 2 or Python 3. In this case it is not mandatory to transform all
extensions at once.
I had a look into the source code and I think it is relatively easy to implement
this.

**Comment by clefebvre** [comment]
@brmmm3 that's interesting. I never really thought about this. This would be great.

**Comment by brmmm3** [comment]
I've already modified the code. It was easy. A bit more tricky now is the
modification of the build system. I'm not aware of autoconf and I have no
time to learn it. Would be great if someone else could do this. I can
pastebin the code when I am back home.

Regards

Martin

Am 26.09.2016 11:49 Vorm. schrieb "Clement Lefebvre" <
notifications@github.com>:

@brmmm3 <https://github.com/brmmm3> that's interesting. I never really
thought about this. This would be great.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/linuxmint/nemo-extensions/pull/145#issuecomment-249526719>,
or mute the thread

**Comment by brmmm3** [comment]
The easiest and IMHO cleanest way to support both is to modify Doplers nemo-
python plugin so that all occurrance of "nemo-python" are renamed to "nemo-
python3" so that installs as nemo-python3 and the extension search path
is /usr/share/nemo-python3/extensions.
I've done the changes and installed the plugin. But now nemo is crashing.
Setting NEMO_PYTHON_DEBUG to misc shows the following output:
nemo_module_initialize: entered
nemo_python_load_dir: entered dirname=/usr/share/nemo-python/extensions
nemo-python:g_module_open /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
nemo-python:Py_Initialize
nemo-python:PySys_SetArgv
nemo-python:Sanitize the python search path
nemo-python:init_pygobject
nemo-python:import nemo
sys:1: PyGIWarning: Nemo was imported without specifying a version first. Use
gi.require_version('Nemo', '3.0') before import to ensure that the right version
gets loaded.
nemo_python_load_file: entered filename=nemo-media-columns
nemo_python_object_get_type: entered type=ColumnExtension
nemo-python:Loaded python modules
nemo_python_load_file: entered filename=nemo-compare
nemo_python_object_get_type: entered type=NemoCompareExtension
nemo-python:Loaded python modules
nemo_python_load_file: entered filename=nemo_terminal
nemo_python_object_get_type: entered type=NemoTerminalProvider
nemo-python:Loaded python modules
nemo_python_load_file: entered filename=nemo-folder-color-switcher
nemo_python_object_get_type: entered type=ChangeColorFolder
nemo-python:Loaded python modules
nemo_python_load_file: entered filename=nemo-emblems
nemo_python_object_get_type: entered type=EmblemPropertyPage
nemo-python:Loaded python modules
nemo_python_load_dir: entered dirname=/home/martin/.local/share/nemo-
python/extensions
nemo_module_list_types: entered
nemo_python_object_class_init: entered
nemo_python_object_instance_init: entered
nemo_python_object_class_init: entered
nemo_python_object_instance_init: entered
nemo_python_object_class_init: entered
nemo_python_object_instance_init: entered
[Nemo Terminal] I: Initializing the Nemo extension
nemo_python_object_class_init: entered
nemo_python_object_instance_init: entered
Initializing folder-color-switcher extension...
nemo_python_object_class_init: entered
nemo_python_object_instance_init: entered
Initializing nemo-image-converter extension
nemo-python3:nemo_module_initialize
nemo_module_initialize: entered
nemo-python3:nemo_python_load_dir
nemo_python_load_dir: entered Dirname=/usr/share/nemo-python3/extensions
nemo_python_load_dir: entered INIT=0
nemo_python_load_dir: entered NAME0=submenu.py
nemo_python_load_dir: entered NAME1=submenu.py
nemo_python_load_dir: entered MODULE=submenu
nemo-python3:INIT PYTHON
nemo-python3:g_module_open /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
nemo-python3:PY3: Py_Initialize
nemo-python3:PySys_SetArgv
nemo-python3:Sanitize the python search path
nemo-python3:init_pygobject
nemo-python3:import nemo
nemo-python3:nemo_python_load_file
nemo_python_load_file: entered Filename=submenu
Speicherzugriffsfehler
It seems to be crashing at this line:
main_module = PyImport_AddModule("__main__");
I also needed to replace Py_IsInitialized() by the "initialized" status
variable, because the function returns true, although Python3 is not
initialized.
It seems that Python2 functions are called. So currently I'm a little bit
confused what is going wrong here.

**Comment by clefebvre** [comment]
@brmmm3 were you successful in the end, did you manage to make this work?

**Comment by brmmm3** [comment]
Hi,

I've merged the two existing versions of the nemo-python plugin into one to
support both, Python 2 and Python 3. I could create an so-file. But when the
modules for Python 2 and Python 3 (libpython) are loaded nemo-python fails. The
problem is that both libraries are using the same function names. So when the
Python 2 library is loaded, then the symbols for the Python 3 part are
initialized too. Executing a Python 3 script will then cause a segfault.
A solution would be maybe to link statically to both python libraries, but then
the nemo-python plugin would become very big and the solution would not be
really nice. You can find the sources in the attachment.
I think the best solution is to convert all python scripts at once to Python 3.

Best regards,

Martin

**Comment by brmmm3** [comment]
Is there a list of plugins / debian packages which need to be ported to Python
3?

**Comment by clefebvre** [comment]
Ok, well it was worth trying anyhow. Thanks @brmmm3.

I guess we're back to square one. We can try planning that for 3.4.

We're just a few days from 3.2 right now.

**Comment by clefebvre** [comment]
Hi everyone,

Thanks for your patience with this. We'll do the following:

- We'll leave things as they are in Nemo 3.2.
- We'll tackle this migration in preparation for Nemo 3.4.
- We'll warn the rabbitvcs team about our migration to python 3.

That gives rabbitvcs 6 months to anticipate a change. I'm not sure it's enough, assuming it's possible. But it's better than just breaking compatibility overnight.

**Comment by clefebvre** [comment]
No response from rabbitvcs.

I'm happy to discontinue support for it and to move to python3.

**Comment by clefebvre** [comment]
Follow up on this PR. This didn't make it in 3.6. There's no hurdles left for this to happen, it's just that we had to focus on other things so this was left aside. We'll try to migrate to python 3 for 3.8. There's no real hurry, but most of the work is done in this PR already so it's just a matter of re-applying changes and testing things to make sure it all works. We'll get it done eventually, thank you for your patience.

**Comment by adamplumb** [comment]
Hi guys, I'm the maintainer of RabbitVCS.  I made a new RabbitVCS release in June that fixed a bunch of bugs and prepared the way for a future Python3 release, using the six module.  The nemo extension that we have has also been updated, so it should run in python3.  The RabbitVCS UI/backend code still requires python2, for now, but I'm hoping to get some time to work on it.

**Comment by clefebvre** [comment]
Hi @adamplumb, 

Shall we delete the rabbitvcs extension we have in this repository for the time being? We can rely on yours in the meantime and decide late whether to bring it back here or if you want to develop it yourself?

We can proceed to migrate to python3 then also.

**Comment by adamplumb** [comment]
If you want you can open a pull request against the rabbitvcs repo to pull
in any changes you've made and we can maintain the extension in our repo.

**Comment by mtwebster** [comment]
no longer needed

**Comment by mrbesen** [comment]
Is it planned to merge nemo-metadata-tab and the other changes for those plugins?
I would love to be able to see the audio metadata in the properties of a File.

**Comment by mtwebster** [comment]
We don't maintain that plugin - all the ones that [we maintain](https://github.com/linuxmint/nemo-extensions) have been ported to python3.

You'll need to contact whoever maintains that plugin. (I see some PPAs for it but I'm not sure where the actual source is maintained).

**Pull request closed without merging**
